### ISSUE TITLE
Don't run CI on draft pull requests for releases

### ISSUE THREAD

**Issue by jankapunkt** [node-oauth/node-oauth2-server#116]
To prevent CI from failing (and spamming our inbox) on draft pull requests (which can fail as they are reflecting work in progress) we should disable lint/tests etc. when the PR is in draft state.

According to [this discussion](https://github.community/t/dont-run-actions-on-draft-pull-requests/16817) it is solved like so:

```yml
on:
  pull_request:
    types: [review_requested, ready_for_review]
```
